### ISSUE TITLE
Responsiveness issue of about screen

### ISSUE THREAD

**Issue by mariach44** [naveed21-m/construction-Website-Template#4]
1-
![08493367-5eb8-4cad-939b-b31f60a61ec2](https://github.com/user-attachments/assets/dbee4e0e-7a3a-4d66-a86a-af36180c393f)
2-
![4b09ae13-6eee-4665-82af-23f4581bf1bf](https://github.com/user-attachments/assets/71683588-6393-4a43-b94f-f5a9bf122660)
3-
![b9723358-db75-4f43-ad88-f49db121a636](https://github.com/user-attachments/assets/4dba379c-ed2a-4a2a-acc8-3138be57e162)
4-
![7c53926f-b35e-4f71-9f03-c7c471b12018](https://github.com/user-attachments/assets/b1146bf0-0338-4af3-a291-1a3e805506f1)

**Comment by mariach44** [comment]
![865dc052-2519-41f9-988d-87ba66837b81](https://github.com/user-attachments/assets/544c14f7-1b2c-4c48-9f7d-5c8407ba5e70)

@naveed21-m

**Comment by naveed21-m** [comment]
in figma ![image](https://github.com/user-attachments/assets/f76c5b82-9988-4b3f-8bc7-e72263f2c59a)
